=== JoachimFalk/systemoc-SysteMoC/systemoc-sqr/cmx.dtd
<!ELEMENT vpcconfiguration (resultfile?,measurefile?,resources,mappings)>

<!ELEMENT resultfile EMPTY>
<!ATTLIST resultfile
name CDATA #REQUIRED>

<!ELEMENT measurefile EMPTY>
<!ATTLIST measurefile
name CDATA #REQUIRED>

<!ELEMENT resources (component)*>

<!ELEMENT component ((configuration*, defaultconfiguration?)?, attribute*)>
<!ATTLIST component
name ID #REQUIRED
type CDATA #REQUIRED
scheduler CDATA #REQUIRED>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute 
type CDATA #REQUIRED
value CDATA #REQUIRED>

<!ELEMENT configuration (component)*>
<!ATTLIST configuration
name ID #REQUIRED
loadtime CDATA "0 ns"
storetime CDATA "0 ns">

<!ELEMENT defaultconfiguration EMPTY>
<!ATTLIST defaultconfiguration
name CDATA #REQUIRED>

<!ELEMENT mappings (mapping)*>

<!ELEMENT mapping (attribute)*>
<!ATTLIST mapping
source CDATA #REQUIRED
target IDREF #REQUIRED>

=== JoachimFalk/systemoc-SysteMoC/systemoc-sqr/configuration.cmx.xml
<?xml version="1.0"?>
<!DOCTYPE configuration SYSTEM "cmx.dtd">
<configuration>
 <resultfile name=""/>
 <measurefile name=""/>

 <resources>
  <component name="Component1" type="threaded" scheduler="RoundRobin">
   <attribute type="timeslice" value="20ns"/>
  </component>
 </resources>

 <mappings>
  <mapping source="top.al.approx" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_approx::approx" value="100"/>
  </mapping>

  <mapping source="top.al.dup" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_dup::dup" value="100"/>
  </mapping>

  <mapping source="top.al.sqrloop" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_sqrloop::copy1" value="100"/>
    <attribute type="m_sqrloop::copy2" value="100"/>
    <attribute type="m_sqrloop::store" value="100"/>
  </mapping>

  <mapping source="top.sink" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_sink::sink" value="100"/>
  </mapping>

  <mapping source="top.src" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_src::src" value="100"/>
  </mapping>

 </mappings>
</configuration>
