=== JoachimFalk/systemoc-SysteMoC/systemoc-par/cmx.dtd
<!ELEMENT configuration (resultfile?,measurefile?,resources,mappings)>

<!ELEMENT resultfile EMPTY>
<!ATTLIST resultfile
name CDATA #REQUIRED>

<!ELEMENT measurefile EMPTY>
<!ATTLIST measurefile
name CDATA #REQUIRED>

<!ELEMENT resources (component)*>

<!ELEMENT component (attribute)*>
<!ATTLIST component
name CDATA #REQUIRED
type CDATA #REQUIRED
scheduler CDATA #REQUIRED>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute 
type CDATA #REQUIRED
value CDATA #REQUIRED>

<!ELEMENT mappings (mapping)*>

<!ELEMENT mapping (attribute)*>
<!ATTLIST mapping
source CDATA #REQUIRED
target CDATA #REQUIRED>

=== JoachimFalk/systemoc-SysteMoC/systemoc-par/configuration.cmx.xml
<?xml version="1.0"?>
<!DOCTYPE configuration SYSTEM "cmx.dtd">
<configuration>
 <resultfile name=""/>
 <measurefile name=""/>

 <resources>
   <component name="sink" type="threaded" scheduler="FCFS"/>
   <component name="src" type="threaded" scheduler="FCFS"/>
   <component name="mod_disp" type="threaded" scheduler="FCFS"/>
   <component name="mod0" type="threaded" scheduler="FCFS"/>
   <component name="mod1" type="threaded" scheduler="FCFS"/>
   <component name="mod2" type="threaded" scheduler="FCFS"/>
   <component name="mod3" type="threaded" scheduler="FCFS"/>
   <component name="mod4" type="threaded" scheduler="FCFS"/>
 </resources>

 <mappings>

  <mapping source="top.sink" target="sink">
    <attribute type="delay" value="1"/>
  </mapping>

  <mapping source="top.src" target="src">
    <attribute type="delay" value="1"/>
  </mapping>

  <mapping source="top.mod_graph.mod0" target="mod0">
    <attribute type="delay" value="100"/>
  </mapping>

  <mapping source="top.mod_graph.mod1" target="mod1">
    <attribute type="delay" value="100"/>
  </mapping>
    
  <mapping source="top.mod_graph.mod2" target="mod2">
    <attribute type="delay" value="100"/>
  </mapping>
  
  <mapping source="top.mod_graph.mod3" target="mod3">
    <attribute type="delay" value="100"/>
  </mapping>

  <mapping source="top.mod_graph.mod4" target="mod4">
    <attribute type="delay" value="100"/>
  </mapping>

  <mapping source="top.mod_graph.disp" target="mod_disp">
    <attribute type="delay" value="1"/>
  </mapping>

 </mappings>
</configuration>
