=== JoachimFalk/systemoc-SysteMoC/systemoc-idct2d/cmx.dtd
<!ELEMENT vpcconfiguration (resultfile?,measurefile?,templates?, resources,mappings)>

<!ELEMENT resultfile EMPTY>
<!ATTLIST resultfile
name CDATA #REQUIRED>

<!ELEMENT measurefile EMPTY>
<!ATTLIST measurefile
name CDATA #REQUIRED>

<!ELEMENT templates (template+)>

<!ELEMENT template ((attribute|timing)*)>
<!ATTLIST template
  name ID #REQUIRED>

<!ELEMENT reftemplate EMPTY>
<!ATTLIST reftemplate
  name IDREF #REQUIRED
>

<!ELEMENT resources (component)*>

<!ELEMENT component ((configuration*, defaultconfiguration?)?, (attribute|reftemplate)*)>
<!ATTLIST component
name ID #REQUIRED
type CDATA #REQUIRED
scheduler CDATA #REQUIRED>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute 
type CDATA #REQUIRED
value CDATA #REQUIRED>

<!ELEMENT configuration (component)*>
<!ATTLIST configuration
name ID #REQUIRED
loadtime CDATA "0 ns"
storetime CDATA "0 ns">

<!ELEMENT defaultconfiguration EMPTY>
<!ATTLIST defaultconfiguration
name CDATA #REQUIRED>

<!ELEMENT mappings (mapping)*>

<!ELEMENT mapping (attribute|reftemplate|timing)*>
<!ATTLIST mapping
source CDATA #REQUIRED
target IDREF #REQUIRED>

<!ELEMENT timing EMPTY>
<!ATTLIST timing
delay   CDATA #IMPLIED
dii     CDATA #IMPLIED
latency CDATA #IMPLIED
fname   CDATA #IMPLIED>

=== JoachimFalk/systemoc-SysteMoC/systemoc-sqr-double/configuration.cmx.xml
<?xml version="1.0"?>
<!DOCTYPE configuration SYSTEM "cmx.dtd">
<configuration>
 <resultfile name=""/>
 <measurefile name=""/>

 <resources>
  <component name="Component1" type="threaded" scheduler="RoundRobin">
   <attribute type="timeslice" value="20ns"/>
  </component>
 </resources>

 <mappings>
  <mapping source="top.disp" target="Component1">
    <attribute type="delay" value="100"/>
  </mapping>

   <mapping source="top.coll" target="Component1">
    <attribute type="delay" value="100"/>
  </mapping>

  <mapping source="top.a1.approx" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_approx::approx" value="100"/>
  </mapping>

  <mapping source="top.a1.dup" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_dup::dup" value="100"/>
  </mapping>

  <mapping source="top.a1.sqrloop" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_sqrloop::copy1" value="100"/>
    <attribute type="m_sqrloop::copy2" value="100"/>
    <attribute type="m_sqrloop::store" value="100"/>
  </mapping>

  <mapping source="top.a2.approx" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_approx::approx" value="100"/>
  </mapping>

  <mapping source="top.a2.dup" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_dup::dup" value="100"/>
  </mapping>

  <mapping source="top.a2.sqrloop" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_sqrloop::copy1" value="100"/>
    <attribute type="m_sqrloop::copy2" value="100"/>
    <attribute type="m_sqrloop::store" value="100"/>
  </mapping>

  <mapping source="top.sink" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_sink::sink" value="100"/>
  </mapping>

  <mapping source="top.src" target="Component1">
    <attribute type="delay" value="100"/>
    <attribute type="m_src::src" value="100"/>
  </mapping>

 </mappings>
</configuration>

=== JoachimFalk/systemoc-SysteMoC/systemc-par/configuration.cmx.xml
<?xml version="1.0"?>
<!DOCTYPE configuration SYSTEM "cmx.dtd">
<configuration>
 <resultfile name=""/>
 <measurefile name=""/>

 <resources>
  <component name="Component1" type="threaded" scheduler="RoundRobin">
   <attribute type="timeslice" value="20ns"/>
  </component>
 </resources>

 <mappings>

  <mapping source="top.sink" target="Component1">
    <attribute type="delay" value="2"/>
  </mapping>

  <mapping source="top.src" target="Component1">
    <attribute type="delay" value="2"/>
  </mapping>

  <mapping source="top.mod0" target="Component1">
    <attribute type="delay" value="550"/>
  </mapping>

  <mapping source="top.mod1" target="Component1">
    <attribute type="delay" value="450"/>
  </mapping>
    
  <mapping source="top.mod2" target="Component1">
    <attribute type="delay" value="350"/>
  </mapping>
  
  <mapping source="top.mod3" target="Component1">
    <attribute type="delay" value="250"/>
  </mapping>

   <mapping source="top.mod4" target="Component1">
     <attribute type="delay" value="150"/>
   </mapping>

   <mapping source="top.mod5" target="Component1">
     <attribute type="delay" value="50"/>
   </mapping>
		    
  <mapping source="top.disp" target="Component1">
    <attribute type="delay" value="2"/>
  </mapping>

  
 </mappings>
</configuration>

=== JoachimFalk/systemoc-SysteMoC/old-docu/mapping-demo.xml
<?xml version="1.0"?>
<!DOCTYPE configuration SYSTEM "cmx.dtd">
<configuration>
 ...
 <resources>
  <component name="TCMP1" type="threaded" scheduler="RoundRobin">
   <attribute type="timeslice" value="2ns"/>
  </component>
  ...
 </resources>
 <mappings>
  <mapping source="sim_mod.h_hca.h_send_port" target="TCMP1">
   <attribute type="delay" value="2"/>
  </mapping>
  <mapping source="sim_mod.h_hca.h_atu" target="TCMP1">
   <!-- Definiere Ausführungszeit von 2ns für die Aktion
        ib_m_atu::forward_mfetch auf der sim_mod.h_hca.h_atu Komponente -->
   <attribute type="ib_m_atu::forward_mfetch" value="2"/>
   <attribute type="ib_m_atu::forward_rq_mstoreforward_tq_mstore" value="2"/>
   <attribute type="ib_m_atu::process_bthgen_ttdata" value="2"/>
   <attribute type="ib_m_atu::process_rq_ttdata" value="2"/>
   <attribute type="ib_m_atu::process_tq_ttdata" value="2"/>
   <attribute type="ib_m_atu::forward_tq_mstore" value="2"/>
   <attribute type="ib_m_atu::forward_rq_mstore" value="2"/>
   <!-- Definiere Standardausführungszeit von 2ns für alle Aktionen
        denen keine explizite Ausführungszeit zugewiesen worden ist -->
   <attribute type="delay" value="2"/>
  </mapping>
  ...
 </mappings>
</configuration>
