=== JoachimFalk/systemoc-SysteMoC/vpc/automotive-testcase/cmx.dtd
<!ELEMENT vpcconfiguration (resultfile?,measurefile?, resources,mappings, topology?)>

<!ELEMENT resultfile EMPTY>
<!ATTLIST resultfile
name CDATA #REQUIRED>

<!ELEMENT measurefile EMPTY>
<!ATTLIST measurefile
name CDATA #REQUIRED>

<!ELEMENT resources (component)*>

<!ELEMENT component ((configuration*, defaultconfiguration?)?, (attribute)*)>
<!ATTLIST component
name ID #REQUIRED
type CDATA #IMPLIED
scheduler CDATA #REQUIRED>

<!ELEMENT attribute (attribute|parameter)*>
<!ATTLIST attribute 
type CDATA #REQUIRED
value CDATA #IMPLIED>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
type CDATA #REQUIRED
value CDATA #REQUIRED>

<!ELEMENT configuration (component)*>
<!ATTLIST configuration
name ID #REQUIRED
loadtime CDATA "0 ns"
storetime CDATA "0 ns">

<!ELEMENT defaultconfiguration EMPTY>
<!ATTLIST defaultconfiguration
name CDATA #REQUIRED>

<!ELEMENT mappings (mapping)*>

<!ELEMENT mapping (attribute|timing)*>
<!ATTLIST mapping
source CDATA #REQUIRED
target IDREF #REQUIRED>

<!ELEMENT timing EMPTY>
<!ATTLIST timing
powermode CDATA #IMPLIED
delay   CDATA #IMPLIED
dii     CDATA #IMPLIED
latency CDATA #IMPLIED
fname   CDATA #IMPLIED>

<!ELEMENT topology (route)*>
<!ATTLIST topology
tracing     CDATA #IMPLIED
default     CDATA #IMPLIED
>

<!ELEMENT route (hop)*>
<!ATTLIST route
source      CDATA #REQUIRED
destination CDATA #REQUIRED
type        CDATA #IMPLIED
tracing     CDATA #IMPLIED
>

<!ELEMENT hop (attribute|timing)*>
<!ATTLIST hop
name    CDATA #IMPLIED
layer    CDATA #IMPLIED>

=== JoachimFalk/systemoc-SysteMoC/systemoc-sqr/vpc/sqr.vpc.xml
<?xml version="1.0"?>
<!DOCTYPE vpcconfiguration SYSTEM "cmx.dtd">
<vpcconfiguration>

 <resources>
  <component name="CPU" scheduler="FCFS">
   <attribute type="transaction_delay" value="20 ns" />
  </component>

  <component name="Bus" scheduler="FCFS">
   <attribute type="transaction_delay" value="80 ns" />
  </component>

  <component name="Mem" scheduler="FCFS">
   <attribute type="transaction_delay" value="20 ns" />
  </component>
 </resources>

 <mappings>
  <mapping source="sqrroot.a1" target="CPU">
    <timing delay="100 ns"/>
    <timing fname="Src::src" delay="100 ns"/>
  </mapping>

  <mapping source="sqrroot.a2" target="CPU">
    <timing delay="100"/>
    <timing fname="SqrLoop::check"      delay="50 ns" />
    <timing fname="SqrLoop::copyStore"  delay="100 ns"/>
    <timing fname="SqrLoop::copyInput"  delay="100 ns"/>
    <timing fname="SqrLoop::copyApprox" delay="100 ns"/>
  </mapping>

  <mapping source="sqrroot.a3" target="CPU">
    <timing delay="100 ns"/>
    <timing fname="Approx::approx" delay="100 ns"/>
  </mapping>

  <mapping source="sqrroot.a4" target="CPU">
    <timing delay="100 ns"/>
    <timing fname="Dup::dup" delay="100 ns"/>
  </mapping>

  <mapping source="sqrroot.a5" target="CPU">
    <timing delay="100 ns"/>
    <timing fname="Sink::sink" delay="100 ns"/>
  </mapping>

 </mappings>
 <topology tracing="true">
  <route source="sqrroot.a1" destination="cf_sqrroot.a1_sqrroot.a2_1" tracing="false">
    <hop name="CPU" />
    <hop name="Bus" />
    <hop name="Mem" />
  </route>
  <route source="cf_sqrroot.a1_sqrroot.a2_1" destination="sqrroot.a2">
    <hop name="Mem" />
    <hop name="Bus" />
    <hop name="CPU" />
  </route>
  <route source="sqrroot.a2" destination="cf_sqrroot.a2_sqrroot.a3_1">
    <hop name="CPU" />
    <hop name="Bus" />
    <hop name="Mem" />
  </route>
  <route source="cf_sqrroot.a2_sqrroot.a3_1" destination="sqrroot.a3">
    <hop name="Mem" />
    <hop name="Bus" />
    <hop name="CPU" />
  </route>
  <route source="cf_sqrroot.a4_sqrroot.a3_1" destination="sqrroot.a3">
    <hop name="Mem" />
    <hop name="Bus" />
    <hop name="CPU" />
  </route>
  <route source="sqrroot.a3" destination="cf_sqrroot.a3_sqrroot.a4_1">
    <hop name="CPU" />
    <hop name="Bus" />
    <hop name="Mem" />
  </route>
  <route source="cf_sqrroot.a3_sqrroot.a4_1" destination="sqrroot.a4">
    <hop name="Mem" />
    <hop name="Bus" />
    <hop name="CPU" />
  </route>
  <route source="sqrroot.a4" destination="cf_sqrroot.a4_sqrroot.a3_1">
    <hop name="CPU" />
    <hop name="Bus" />
    <hop name="Mem" />
  </route>
  <route source="sqrroot.a4" destination="cf_sqrroot.a4_sqrroot.a2_1">
    <hop name="CPU" />
    <hop name="Bus" />
    <hop name="Mem" />
  </route>
  <route source="cf_sqrroot.a4_sqrroot.a2_1" destination="sqrroot.a2">
    <hop name="Mem" />
    <hop name="Bus" />
    <hop name="CPU" />
  </route>
  <route source="sqrroot.a2" destination="cf_sqrroot.a2_sqrroot.a5_1">
    <hop name="CPU" />
    <hop name="Bus" />
    <hop name="Mem" />
  </route>
  <route source="cf_sqrroot.a2_sqrroot.a5_1" destination="sqrroot.a5">
    <hop name="Mem" />
    <hop name="Bus" />
    <hop name="CPU" />
  </route>
 </topology>
</vpcconfiguration>

=== JoachimFalk/systemoc-SysteMoC/vpc/automotive-energy/vpc/mbmv13.vpc.xml
<?xml version="1.0"?>
<!DOCTYPE vpcconfiguration SYSTEM "cmx.dtd">
<vpcconfiguration>

 <resources>
  <component name="CPU" scheduler="PS">
   <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="5 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>
  
  <component name="CPU_2" scheduler="FCFS">
   <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="1 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>
  
  
    <component name="CPU2" scheduler="FCFS">
   <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="1 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>
  
    <component name="CPU3" scheduler="FCFS">
     <!-- <attribute type="tracing" value="NONE"/> -->
   <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="1 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>

  <component name="Bus" scheduler="PS">
   <attribute type="powermode">
     <attribute type="SHUTDOWN">
	   <parameter type="IDLE"     value="150.00 mW" />
	   <parameter type="RUNNING"  value="150.00 mW" />
	   <parameter type="transaction_delay" value="50 us"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="260.0 mW" />
	   <parameter type="RUNNING"  value="260.0 mW" />
	   <parameter type="transaction_delay" value="50 us"/>
	 </attribute>
	 <attribute type="SLEEP">
	   <parameter type="IDLE"     value="26 mW" />
	   <parameter type="RUNNING"  value="100 W" />
	   <parameter type="transaction_delay" value="50 us"/>
	 </attribute>
	 <attribute type="WAKEUP">
	   <parameter type="IDLE"     value="75.0 mW" />
	   <parameter type="RUNNING"  value="75.0 mW" />
	   <parameter type="transaction_delay" value="50 us"/>
	 </attribute>
   </attribute>
  </component>
   
     <component name="Bus2" scheduler="PS">
   <attribute type="powermode">
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0.0 mW" />
	   <parameter type="RUNNING"  value="0.0 mW" />
	   <parameter type="transaction_delay" value="50 us"/>
	 </attribute>
	  <attribute type="FAST">
	   <parameter type="IDLE"     value="150.00 mW" />
	   <parameter type="RUNNING"  value="150.00 mW" />
	   <parameter type="transaction_delay" value="50 us"/>
	 </attribute>
   </attribute>
   
  </component>
   


  <component name="Mem" scheduler="FCFS">
    <attribute type="powermode">
     <attribute type="FAST">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="1 ns"/>
	 </attribute>
	 <attribute type="SLOW">
	   <parameter type="IDLE"     value="0 mW" />
	   <parameter type="STALLED"  value="0 mW" />
	   <parameter type="RUNNING"  value="0 mW" />
	   <parameter type="transaction_delay" value="3 ns"/>
	 </attribute>
   </attribute>
  </component>
 </resources>


 <mappings>
  <mapping source="sqrroot.a1" target="CPU">
    <timing delay="1 us"  powermode="FAST"/>
    <timing delay="10 us" powermode="SLOW"/>
    <timing fname="Src::src" delay="1 us"   powermode="FAST"/>
    <timing fname="Src::src" delay="10 us"  powermode="SLOW"/>
    <timing fname="Src::reset" delay="1 ns"   powermode="FAST"/>
    <timing fname="Src::reset" delay="1 ns"  powermode="SLOW"/>
  </mapping>

  <mapping source="sqrroot.a2" target="CPU_2">
	<timing delay="1 us"  powermode="FAST"/>
    <timing delay="10 us" powermode="SLOW"/>
    <timing fname="Sink::sink" delay="10 us"  powermode="FAST"/>
    <timing fname="Sink::sink" delay="10 us"  powermode="SLOW"/> 
  </mapping>

  <mapping source="sqrroot.a3" target="Bus">
   <attribute type="priority" value="0" /> 
    <timing delay="1 ns"  powermode="SHUTDOWN"/>
    <timing delay="1 ns" powermode="SLOW"/>
    <timing delay="5 ns" powermode="WAKEUP"/>
    <timing delay="5 ns" powermode="SLEEP"/>
  </mapping>
  
  <mapping source="sqrroot.DPMP" target="Bus">
   <attribute type="priority" value="2" /> 
    <timing delay="0 us"  powermode="SHUTDOWN"/>
    <timing delay="0 us" powermode="SLOW"/>
    <timing delay="0 us" powermode="WAKEUP"/>
    <timing delay="0 us" powermode="SLEEP"/>
    <timing fname="GovernorDPMP::initProcess" delay="1 ns"  powermode="SHUTDOWN"/>
    <timing fname="GovernorDPMP::initProcess" delay="1 ns"  powermode="SLOW"/>
    <timing fname="GovernorDPMP::shutdownPowerMode" delay="1 ns"  powermode="SLOW"/>
    <timing fname="GovernorDPMP::shutdownPowerMode2" delay="1 ns"  powermode="SLOW"/>
    <timing fname="GovernorDPMP::wakeupPowerMode" delay="1 ns"  powermode="SLEEP"/>
    <timing fname="GovernorDPMP::wakeupPowerMode" delay="1 ns"  powermode="SHUTDOWN"/>
    <timing fname="GovernorDPMP::normalPowerMode" delay="30 us"  powermode="SLEEP"/>
    <timing fname="GovernorDPMP::normalPowerMode" delay="30 us"  powermode="SHUTDOWN"/>
  </mapping>

  <mapping source="sqrroot.DPMP2" target="CPU3">
    <timing delay="15 us"  powermode="FAST"/>
    <timing delay="15 us" powermode="SLOW"/>
  </mapping>
  
   <mapping source="sqrroot.Pulse" target="CPU2">
    <timing delay="1 us"  powermode="FAST"/>
    <timing delay="1 us" powermode="SLOW"/>
    <timing fname="TestClass::src" delay="1 ns"   powermode="FAST"/>
    <timing fname="TestClass::src" delay="10 ns"  powermode="SLOW"/>
  </mapping>
  
 </mappings>
 
 
 <topology tracing="vcd" default="ignore">
  <route source="sqrroot.a1" destination="channel" tracing="true">
    <hop name="CPU" >
    	<timing latency="1 us" dii="1 us" />
    </hop>
    <hop name="Mem" >
    	<timing latency="59 us" dii="59 us" />
    </hop>
    <hop name="Bus2" > 
    	<attribute type="priority" value="3" /> 
    	<timing latency="50 us" dii="50 us" powermode="FAST"/>
    	<timing latency="50 us" dii="50 us" powermode="SLOW"/>
    	<timing latency="50 us" dii="50 us" powermode="FAST"/>
    </hop> 
  	<hop name="CPU_2" >
    	<timing latency="60 us" dii="60 us" />
    </hop>
  </route>
  
    <route  source="sqrroot.Pulse" destination="pulser">

  </route>
  
 </topology>
 
</vpcconfiguration>
